### ISSUE TITLE
Really weird location map

### ISSUE THREAD

**Issue by E3V3A** [tripleblindmarket/private-kit#211]
I opened app and let it lock gps.
This is what I got on the map after...

![wtf1](https://user-images.githubusercontent.com/194392/77604590-92728400-6f1b-11ea-9f5e-39e3417c9385.jpg)

---

*"If I was on LSD or mushrooms this would be cool, but I'm just trying to prevent being on COVID."*

**Comment by tremblerz** [comment]
Hey, this is expected. Instead of putting all markers in the same place it draws a circle around and lines denote where they actually converge. The library is handling this part of the visualization. This is something that we can get rid of by removing all the redundant points but I am not sure if it should be done or not.

**Comment by E3V3A** [comment]
>  Instead of putting all markers in the same place it draws a circle around and lines denote where they actually converge. 

ok, doesn't make much sense. maybe artifact of quick development. It should be easy to check if new position has changed (within X meters, lets say) since last one. Can probably even checked by SQL in sqlite3 itself.

**Comment by penrods** [comment]
This feature has had a major overhaul in the UI.  I'm going to close this issue, please reopen if you see problem after the next build comes out.
