### ISSUE TITLE
Refresh map visualization when user has pressed back and goes to the screen again

### ISSUE THREAD

**Issue by tremblerz** [tripleblindmarket/private-kit#253]
Right now if I press back and go to the check overlap screen again, it shows same location as no `state` has changed from React's perspective. However, my location might have changed meanwhile and rendering old data becomes sort of useless.
Solution:
In overlap.js, Check component mount and refresh the state by placing markers everytime the component is mounted.
NOTE: This is just one way of implementing, there could be more elegant ways as well.

**Comment by thetimbanks** [comment]
I did something similar on the Export screen in this PR https://github.com/tripleblindmarket/private-kit/pull/244

I converted the component to a functional component in order to use `useFocusEffect` to check when the view came in to focus. I will try to take a look at this over the weekend if I have some free time.

**Comment by thetimbanks** [comment]
Got the `Overlap` component updated so it refreshes the markers each time the view comes in to focus #259
