### ISSUE TITLE
Bring up the location data collapse PR changes back

### ISSUE THREAD

**Issue by tremblerz** [tripleblindmarket/private-kit#51]

**Comment by tremblerz** [comment]
See the changes proposed in LocationTracking.js https://github.com/tripleblindmarket/private-kit/pull/35/files

**Comment by tushar-dadlani** [comment]
can you provide some more examples? This looks like a UI/UX change.

**Comment by penrods** [comment]
That code got lost in PR merge when the GPS point "curate" code moved from views/LocationTracking.js to services/LocationService.js.   The curate was in PR #35 in the new lines from 70-85:  https://github.com/tripleblindmarket/private-kit/pull/35/files#diff-727aee301c7a491d08372f19508dfde6R70

If you can tackle it in the next little bit I'll review.  Otherwise I'll go after it myself.

**Comment by penrods** [comment]
Fixed by #55
